# Generated by Django 6.0 on 2026-01-03 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='awaiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
