# Generated by Django 5.2.9 on 2026-01-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.CharField(choices=[('Introduction to Software Engineering', 'Introduction to Software Engineering'), ('Frontend Web Development(REACT)', 'Frontend Web Development(REACT)'), ('Backend Web Development (Python)', 'Backend Web Development (Python)'), ('Backend Web Development (Node.js)', 'Backend Web Development (Node.js)')], max_length=100),
        ),
    ]
